#!/bin/sh

image_dir="/home/nastet/Desktop/wpic/$(date +%Y-%m-%d)"
image_cmd="$(which fswebcam) --quiet --set brightness=80% --no-banner"

#Creating file hierarchy
mkdir -p "${image_dir}"

trap 'echo "SIGINT called, exiting"' SIGINT

echo="Running..."
(
while [ 1 ] ; do
    ${image_cmd} "${image_dir}/$(date +%H-%M-%S).jpg"; 
    sleep 2;
done
)
